CREATE TABLE ESCOLA.ALUNO(
	CPF VARCHAR(14),
	MATRICULA INT,
	NOM_ALUNO VARCHAR(100),
	DT_NASC DATE,
	NOM_PAI VARCHAR(100),
	NOM_MAE VARCHAR(100),
	EMAIL VARCHAR(100),
	TURMA INT,
	TURMA_NOTAS INT,
	SITUACAO INT,
	CONTRAINT ALUNO_CPF_PK PRIMARY KEY (CPF)
	
)